[package]
name = "day13"
version = "0.1.0"
edition = "2021"

[dependencies]
measure_time = "0.8.2"
serde_json = "1.0.89"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
