[package]
name = "day19"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.10.0"
fxhash = "0.2.1"
itertools = "0.10.5"
log = "0.4.17"
measure_time = "0.8.2"
regex = "1.7.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
