[package]
name = "day16"
version = "0.1.0"
edition = "2021"

[dependencies]
dot_graph = "0.2.3"
measure_time = "0.8.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
