[package]
name = "day06"
version = "0.1.0"
edition = "2021"

[dependencies]
lending-iterator = "0.1.6"
measure_time = "0.8.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
